spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8088/realms/ems}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8088/realms/ems/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  endpoint:
    health:
      probes:
        enabled: true

app:
  routes:
    user-service-base-url: ${APP_ROUTES_USER_SERVICE_BASE_URL:http://localhost:8080}
    ticket-service-base-url: ${APP_ROUTES_TICKET_SERVICE_BASE_URL:http://localhost:8081}
    event-service-base-url: ${APP_ROUTES_EVENT_SERVICE_BASE_URL:http://localhost:8082}
    payment-service-base-url: ${APP_ROUTES_PAYMENT_SERVICE_BASE_URL:http://localhost:8084}
    notification-service-base-url: ${APP_ROUTES_NOTIFICATION_SERVICE_BASE_URL:http://localhost:8085}
    importer-service-base-url: ${APP_ROUTES_IMPORTER_SERVICE_BASE_URL:http://localhost:8086}
