apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-config
  namespace: ems
  labels:
    app.kubernetes.io/name: ems-config
    app.kubernetes.io/part-of: event-tech
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  INTERNAL_HTTP_SCHEME: http
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  APP_S3_REGION: us-east-1
  APP_RECEIPTS_BUCKET: ems-payment-receipts
