apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ems
resources:
  - namespace.yaml
  - configmap.yaml
  - infra/postgres.yaml
  - infra/platform.yaml
  - apps/services.yaml

configMapGenerator:
  - name: ems-keycloak-realm
    files:
      - ems-realm.json=../../keycloak/ems-realm.json
