apiVersion: v1
kind: Secret
metadata:
  name: ems-secrets
  namespace: ems
  labels:
    app.kubernetes.io/name: ems-secrets
    app.kubernetes.io/part-of: event-tech
type: Opaque
stringData:
  USER_SERVICE_DB_PASSWORD: replace-in-environment
  TICKET_SERVICE_DB_PASSWORD: replace-in-environment
  EVENT_SERVICE_DB_PASSWORD: replace-in-environment
  PAYMENT_SERVICE_DB_PASSWORD: replace-in-environment
  NOTIFICATION_SERVICE_DB_PASSWORD: replace-in-environment
  IMPORTER_SERVICE_DB_PASSWORD: replace-in-environment
  APP_SECURITY_KEK_BASE64: replace-with-256-bit-base64-aes-key
  APP_S3_ACCESS_KEY: replace-in-environment
  APP_S3_SECRET_KEY: replace-in-environment
  KEYCLOAK_ADMIN_PASSWORD: replace-in-environment
